### ISSUE TITLE
use new field "createTime" instead of id in pipelineDAO and elsewhere

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/FREMECommon#12]
In order to implement #11 there should be no other use of the id.

Please assgin to me, when implemented.

**Comment by jnehring** [comment]
@ArneBinder can we add the createtime to all ownedresources?

**Comment by ArneBinder** [comment]
Of course. I will implement this.

**Comment by ghsnd** [comment]
Now it is implemented so that the pipelines make use of the field "createTime" in stead of "id". The id still exists and is used as before, except that it doesn't mean time of creation anymore. Or should the id as it is now completely dissapear?

**Comment by ArneBinder** [comment]
>Now it is implemented so that the pipelines make use of the field "createTime" in stead of "id".
Thanks, I also fixed [this line](https://github.com/freme-project/FREMECommon/blob/master/src/main/java/eu/freme/common/persistence/dao/PipelineDAO.java#L47).
>Or should the id as it is now completely dissapear?
No, it's all right. Now we can add auto increment via hibernate to the id what should fix https://github.com/freme-project/e-Link/issues/52
