### ISSUE TITLE
write a readme paragraph about OwnedResource

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/FREMECommon#15]
write a readme paragraph about OwnedResources covering the following topics:
* creation of new model/DAO/repository classes
* building a controller
* testing the controller

@jnehring ok?

**Comment by jnehring** [comment]
This paragraph should be part of the article in https://github.com/freme-project/Documentation/issues/144

**Comment by ArneBinder** [comment]
finished. @jnehring can we close this?

**Comment by jnehring** [comment]
thank you
