### ISSUE TITLE
persistence: remove all child objects when user is removed

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/FREMECommon#17]
because of implementation of https://github.com/freme-project/basic-services/issues/22 this does not work anymore. The User model can not contain references to the child objects and infere orphanremoval automaticaly because they are not in the "main" FREMECommon anymore.

It should be done via an query against the entityManager in the UserDAO.

**Comment by jnehring** [comment]
I added the @ OnDelete  annotation to OwnedResource. Now every OwnedResource should get deleted automatically when the owner gets deleted.
