### ISSUE TITLE
Removed dependency on persistence-api

### ISSUE THREAD

**Issue by jnehring** [freme-project/FREMECommon#18]
I removed dependency on javax.persistence.persistence-api in [this commit](https://github.com/freme-project/FREMECommon/commit/32e4971bb27f60abbdb1dcbf17e3cfdb4efa5c6f). FREME packages can no longer start with this jar file on the class path.

@ArneBinder you added this dependency. Please check if you need it.

**Comment by ArneBinder** [comment]
@jnehring I'm really sorry for this, it was an error of my IDE. It could not resolve this dependeny. I deleted my whole local repository, now it works.

**Comment by jnehring** [comment]
no problem ;)
