### ISSUE TITLE
[freme-dev] OwnedResource entities not accessible

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/FREMECommon#20]
Templates, pipelines and filters are not accessible. But the database contains entities.

**Comment by jnehring** [comment]
Probably the problem originates from within https://github.com/freme-project/freme-packages/issues/9 . Right now freme-dev uses an in-memory database which is cleared after every restart.

**Comment by jnehring** [comment]
problem solved through solving https://github.com/freme-project/freme-packages/issues/9

**Comment by jnehring** [comment]
The problem was solved only for e-link templates, not for pipelines and filters.

**Comment by ArneBinder** [comment]
Fixed the filters. We renamed the entity to `sparqlconverter` some weeks ago. I imported the content of the table `filter` into `sparqlconverter`. Can we delete the `filter` table?

**Comment by ArneBinder** [comment]
Fixed pipelines, also this db schema changed a bit. 

Summed up steps to migrate to **achitecture-update**:
* filter/sparqlconverter:
  * just rename table `filter` to `sparqlconverter`
* pipeline:
  * rename column `serializedRequests` to `requests`
  * change datatype of `id` and `creation_time` to `BIGINT(20)`

**Comment by jnehring** [comment]
We need to perform the same changes in the database schema before the release of freme 0.6, so I created https://github.com/freme-project/FREMECommon/issues/21. i deleted the filter table. This issue is done.
