### ISSUE TITLE
Update live database schema

### ISSUE THREAD

**Issue by jnehring** [freme-project/FREMECommon#21]
Before the release of FREME 0.6 we have to update the dababase schema of pipelines and sparql filters according to https://github.com/freme-project/FREMECommon/issues/20

Holds for datasets also

**Comment by jnehring** [comment]
Please check the list of database changes from https://github.com/freme-project/FREMECommon/issues/20#issuecomment-205897368 and see if I need to update something else.

**Comment by ArneBinder** [comment]
I have checked the list, it is still correct. Furthermore, the empty tables `dataset` and `dataset_simple` can be removed.

**Comment by jnehring** [comment]
done during yesterdays release
