### ISSUE TITLE
Simplify maven version management

### ISSUE THREAD

**Issue by jnehring** [freme-project/FREMECommon#24]
I want to make the version management of FREME more simple. I want to define default versions for all FREME artifacts in freme-parent. So the version of freme-parent determines the version numbers of all FREME artifacts. This has advantages:

* Each version of freme-parent defines versions that are compatible to each other.
* It is easier to create and update FREME packages because you do not need to care for the version numbers of each individual artifact.
* It is easier to manage the version numbers because they are stored in a central place.
* It is faster and less error-prone to perform a release.

**Comment by jnehring** [comment]
I performed the changes in all FREME maven artifacts. During the next release I will test how good this works out and document how the release process works with the new setup.

**Comment by jnehring** [comment]
These changes need to be reflected in the developers guides:

http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-developers/how-to-write-an-eservice.html
http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-developers/creating-a-basic-service.html

**Comment by ArneBinder** [comment]
This is implemented.
