### ISSUE TITLE
Allow setting admin password by configuration

### ISSUE THREAD

**Issue by jnehring** [freme-project/FREMECommon#25]
When the admin username / password is set via configuration (parameters admin.create, admin.username, admin.password) and the admin username already exists, then the admins password should be updated according to the configuration parameter. This behaviour needs to be noted in the [documentation](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/configuration-options.html). The code to create the admin user is [here](https://github.com/freme-project/FREMECommon/blob/master/src/main/java/eu/freme/common/security/SecurityConfig.java#L88).

**Comment by ArneBinder** [comment]
implemented.

**Comment by ArneBinder** [comment]
@jnehring please review the [initialising freme article](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/initialising-freme.html) and [admin parameter section](http://api-dev.freme-project.eu/doc/knowledge-base/freme-for-sysadmins/configuration-options.html#admin).

**Comment by jnehring** [comment]
Looks good, thank you
