### ISSUE TITLE
Fix zabbix logging configuration

### ISSUE THREAD

**Issue by jnehring** [freme-project/FREMECommon#27]
Currently zabbix logs too much. Please reduce the log level so the log files do not get too big. Consider the possibility to leave the log level in place but change the behaviour to be a rolling logfile, so after e.g. 500 mb of log size old log messages get deleted.

**Comment by ArneBinder** [comment]
I set the `LogFileSize` to 500 (see [here](https://www.zabbix.com/documentation/3.0/manual/appendix/config/zabbix_server)) and reloaded the config via `sudo zabbix_server -R config_cache_reload`, like described [here](https://www.zabbix.com/documentation/3.0/manual/concepts/server).

**Comment by ArneBinder** [comment]
Wait until `zabbix_server.log` is grown to 500mb and check, if log rotation works.

**Comment by ArneBinder** [comment]
The log file still grows above 5mb.

**Comment by ArneBinder** [comment]
I reset zabbix `LogFileSize=0` and added `size 500m` to `/etc/logrotate.d/zabbix-server-mysql`. But this seems to have no effect either.

**Comment by ArneBinder** [comment]
Removed old rotated logs.

**Comment by ArneBinder** [comment]
Switched to daily rotation.

**Comment by jnehring** [comment]
This seems to be quiet complicated. How about deleting part of the logs via cronjob once per day?

**Comment by jnehring** [comment]
This is finished.
