### ISSUE TITLE
Update list of 3rd party libraries

### ISSUE THREAD

**Issue by jnehring** [freme-project/FREMECommon#32]
Please update the list of 3rd party libraries for each repository.

**Comment by ArneBinder** [comment]
@jnehring I modified the [Maven Apache License Util](https://github.com/ArneBinder/MavenApacheLicenseUtil) to adapt the changes of the architecture update. I prepared a [licenses.tsv](https://drive.google.com/open?id=0B0tkh6Bg_AK5MzdKUXRCLW9pUDQ) including license annotation for nearly all modules included in FREME. Just `org.linkeddatafragments:ldf-client:0.1` is missing. Some (FREME) versions are still snapshots, so I recommend to update the `license.tsv` during the release again. 

Furthermore, the documentation is not yet included in the `license.tsv`.

**Comment by ArneBinder** [comment]
I added the missing infromation for `org.linkeddatafragments:ldf-client:0.1` and some modules for the documentation (Saxon-CE, backbone, bootstrap, handlebars, highlight, html-proofer, htmlEncode, jekyll, jquery, jquery-ui, jquery.ba-bbq, jquery.smartmenus, jquery.wiggle, js-yaml, jsoneditor, lodash, marked, pages-gem, smartmenus-bootstrap, swagger-ui, underscore).

**Comment by ArneBinder** [comment]
added 3rd party license files.

**Comment by ArneBinder** [comment]
@jnehring should the license file headers be updated / added, too? 
This could be done easily by executing the maven goal `license:format` at every repo root. I moved the configuration for the plugin (`com.mycila:license-maven-plugin`) from FREMECommon to freme-parent, so this works with projects using `freme-parent:0.10-SNAPSHOT` as parent.

**Comment by jnehring** [comment]
yes the license headers should be updated to. @bgrusdt please update the license headers.

**Comment by jnehring** [comment]
Execute mvn license.format first, then mvn test. Then commit and push to git.

Please update these repositories

* freme-parent
* basic-services
* e-services

**Comment by bgrusdt** [comment]
I added the license headers to the three repositories, freme-parent, basic-services and e-services. There are no problems in Jenkins.
