### ISSUE TITLE
[OwnedResourceManagingController] abstract method will break code

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/FREMECommon#37]
@sandroacoelho is there any reason for [this commit](https://github.com/freme-project/FREMECommon/commit/e4529874e6915f825baf46920d2b01e78d3daa7d)? It breaks implementations of `OwnedResourceManagingController` because this method is not implemented (and not necessary) in all other cases except freme-ner, so the modules are no longer compatible with `FREMECommon:0.11-SNAPSHOT`. 

Affected modules:
* e-link (e-services)
* pipelines (basic-services)
* sparql-converters (basic-services)
* xslt-converter (basic-services)

Currently, there are no compiler warnings, because the new freme-parent (0.11-SNAPSHOT), which integrates the modified version (0.11-SNAPSHOT) of FREMECommon, is not yet used by any of the modules mentioned above.

**Comment by jnehring** [comment]
I removed the abstract modifier. As @ArneBinder pointed out it causes compilation errors all over FREME and I dont see an advantage.

@sandroacoelho what do you want to achieve?

**Comment by sandroacoelho** [comment]
Hi @jnehring , @ArneBinder 

When we delete some dataset from FREME-NER, it just removes from MySQL. I guess that 
```protected void preDelete(DatasetMetadata entity) ```was projected to keep consistency between MySQL - Solr as we can see at [FremeNerManageDatasets.java](
https://github.com/freme-project/freme-ner/blob/11ba41dda8d3571e3c7ac2d1facd23319b282592/src/main/java/org/elinker/core/rest/FremeNerManageDatasets.java#L156), isn't it?

If yes, we should think in a solution to solve this issue in FREME-NER.

**Comment by jnehring** [comment]
Are you sure that the preDelete function of FremeNerManageDataset is not executed? Maybe you can add a log message to the function. When you delete a dataset and you do not see the log message then you know it is not executed.

**Comment by sandroacoelho** [comment]
Hi @jnehring ,

I tested it using our FREME-DEV instance and figure out that is not working as well. Then I called preDelete using JUNIT and the dataset was deleted

**Comment by m1ci** [comment]
@sandroacoelho 
1) tried to create dataset at FREME dev using the tutorial page https://api-dev.freme-project.eu/doc/tutorials/entity-recognition-against-custom-dataset.html - it was successfully created
2) checked if solrdev successfully processed the dataset - it was successfully processed
3) remove the dataset using the tutorial page https://api-dev.freme-project.eu/doc/tutorials/entity-recognition-against-custom-dataset.html - it was successfully removed
4) checked if solrdev successfully removed the dataset - it was successfully removed

So I think it works OK. maybe you are doing smth wrong?

**Comment by sandroacoelho** [comment]
Hi @m1ci ,

I am wrong. It works through tutorial page.
