### ISSUE TITLE
developer tags in pom.xml files

### ISSUE THREAD

**Issue by jnehring** [freme-project/FREMECommon#42]
This issue collects all developer annotations (developer name + email address) for all freme artifacts.

**Comment by m1ci** [comment]
For FREME NER and e-Entity pom:
- Milan Dojchinovski (milan.dojchinovski@fit.cvut.cz)
- Sandro Coelho (sandroacoelho@gmail.com )

For e-Services pom and e-link and dbpedia-spotlight poms:
- Milan Dojchinovski (milan.dojchinovski@fit.cvut.cz)

In dataset-conversion-scripts pom for [grid-scripts pom](https://github.com/freme-project/dataset-conversion-scripts/blob/master/grid-scripts/pom.xml) 
- Milan Dojchinovski (milan.dojchinovski@fit.cvut.cz)

and for [orcid-scripts](https://github.com/freme-project/dataset-conversion-scripts/blob/master/orcid-scripts/pom.xml) add:
- Milan Dojchinovski (milan.dojchinovski@fit.cvut.cz)
- Martin Brummer (bruemmer@informatik.uni-leipzig.de)

**Comment by pheyvaer** [comment]
e-Publishing, e-Services:
Gerald Heasendonck (gerald.haesendonck@ugent.be)
Pieter Heyvaert (pheyvaer.heyvaert@ugent.be)

pipelines, batch-processing-tool:
Gerald Heasendonck (gerald.haesendonck@ugent.be)

**Comment by katia-vistatec** [comment]
VistaTEC developers for e-internationalization:

Marta Borriello (marta.borriello@vistatec.com)
Katia Iacomussi (katia.iacomussi@vistatec.com)

**Comment by jnehring** [comment]
Add the developers Jan Nehring (jan.nehring@dfki.de), Jonathan Sauder (jonathan.sauder@dfki.de), Arne Binder (arne.binder@dfki.de), Britta Grusdt (choose your favorite email)

* basic-services/package-maker: Jan
* basic-services/test-helper: Jan, Arne, Jonathan
* basic-services/controllers/nifconverter: Arne
* basic-services/controllers/sparql-converters: Arne
* basic-services/controllers/users: Jan, Arne
* basic-services/controllers/xslt-converter: Arne
* basic-services/filters/cors-filter: Jan
* basic-services/filters/logging: Jonathan
* basic-services/filters/postprocessing: Arne
* basic-services/filters/rate-limiter: Jonathan
* basic-services/filters/internationalization-filter: Jan
* basic-services/filters/proxy-filter: Jan
* basic-services/filters/urlsupport-filter: Britta
* FREMECommon: Jan, Arne, Jonathan
* freme-parent: Jan
* e-services/tilde: Jan
* freme-packages/broker-dev: Jan
* freme-packages/freme-full: Jan
* freme-packages/freme-ner-dev: Jan
* freme-packages/broker-local: Jan

I think we have collected all developer information. @bgrusdt please add the information to the pom.xml files

**Comment by bgrusdt** [comment]
This is done.
