### ISSUE TITLE
Missing data on the live server

### ISSUE THREAD

**Issue by jnehring** [freme-project/FREMECommon#43]
Some data is missing in the live version

* https://api.freme-project.eu/data
* https://api.freme-project.eu/datasets
* https://api.freme-project.eu/solr.tar.gz

Please copy the data from our old live server to your new server.

**Comment by jnehring** [comment]
This was done by @munnellg . But I mentioned that some data was missing in the /datasets folder which I copied to the datasets folder. Can you please execute from rv1460.1blu.de server

```
rsync -r -u /var/www/html/datasets ADAPT-SERVER
```

One file that is missing is 

http://api.freme-project.eu/datasets/gwpp/gwpp-dataid.ttl
http://rv1460.1blu.de/datasets/gwpp/gwpp-dataid.ttl

**Comment by m1ci** [comment]
> One file that is missing is
> http://api.freme-project.eu/datasets/gwpp/gwpp-dataid.ttl
> http://rv1460.1blu.de/datasets/gwpp/gwpp-dataid.ttl

@jnehring  Should I deliver this? or we have it?

**Comment by jnehring** [comment]
The file is already there. I copied them today morning. The two links are for @munnellg so he can test if the right data was transfered.

**Comment by munnellg** [comment]
@jnehring I've added that file to our server. It should be available to you now

**Comment by jnehring** [comment]
Its not only this file but also some others. E.g. https://api.freme-project.eu/datasets/dbpedia-abstracts/dbpedia-abstracts-dataid.ttl . There are quiet a lot of files. I uploaded all data to http://rv1460.1blu.de/datasets . When you execute the rsync command i posted above it should transfer all missing files to your server.

**Comment by munnellg** [comment]
@jnehring Ah, sorry about that. Should be all fixed now!

**Comment by jnehring** [comment]
thanks. now its fine!
