### ISSUE TITLE
Providing the owner of a template

### ISSUE THREAD

**Issue by ArneBinder** [freme-project/FREMECommon#8]
Should we do this? A template naturaly does not know anything about it's owner...

**Comment by jnehring** [comment]
I am not exactly sure what you mean.

Maybe the question is: Should the API endpoints GET /e-link/templates and GET /e-link/templates/{id} return the owner of the template. Then my answer is: Yes please implement it. The endpoints should just return the owner name as string and not the whole user object.

**Comment by ArneBinder** [comment]
Ok I implement it like you said.

**Comment by ArneBinder** [comment]
Implemented for outformat=JSON (other outformats aren't adapted, bacause of [this issue](https://github.com/freme-project/e-Link/issues/48)).
